pipeline {
    agent any

    environment {
        // Declare a global variable to hold the closure
        myFunc = null
    }

    stages {
        stage("Initialize") {
            steps {
                script {
                    // Define the closure and assign it to a global variable
                    myFunc = { text -> 
                        echo "${text}"
                    }

                    // Call the closure in this stage
                    myFunc("Hello from closure function call in Initialize")
                }
            }
        }

        stage("Demo") {
            steps {
                script {
                    // Call the closure in this stage
                    myFunc("Hello from closure function call in Demo")
                }
            }
        }
    }
}
