pipeline {
    agent any
    
    parameters {
        string(defaultValue: "TEST", description: "Which env to deploy to?", name:"deployEnv")
        }
    
    
    stages {
        stage("Demo") {
            steps {
                echo "string is set to: ${params.deployEnv}"
            }
        }
    }

}