pipeline {

    agent any

    environment {
        // global vars
        myString = "Hello World"
        myNumber = 1000
        myBool = true
    }


    stages {

        stage("Demo One") {
            steps {
                script {
                    echo "myString: ${myString}"
                    echo "myNumber: ${myNumber}"

                }
            }
        }

        stage("Demo Two") {
            steps {
                script { // using groovy script allows us to use conditionals
                    // local var
                    localVar = "This is local variable"
                    echo "${localVar}"

                    def buildStatus = true
                    if (buildStatus) {
                        echo "Build successful"
                    } else {
                        echo "Build failed"
                    }

                }
            }
        }


    }


}